apiVersion: apps/v1
kind: Deployment
metadata:
  name: project123-deployment
  labels:
    app: project123
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project123
  template:
    metadata:
      labels:
        app: project123
    spec:
      containers:
      - name: nodeserver
        image: nivigh/project123:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: project123-service
spec:
  selector:
    app: project123 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
